---
name: "BWA"
dataIns:
- name: "s3bucket"
  type: "string"
  source: "s3bucket"
- name: "files"
  type: "collection"
  source: "files"
- name: "numSplits"
  type: "number"
  source: "numSplits"
workflowBody:
- function:
    name: "bwa-mask"
    type: "Collection"
    dataIns:
    - name: "s3bucket"
      type: "string"
      source: "BWA/s3bucket"
    - name: "files"
      type: "string"
      source: "BWA/files"
    - name: "numSplits"
      type: "number"
      source: "BWA/numSplits"
    dataOuts:
    - name: "s3bucket"
      type: "string"
    - name: "s3splitkeys"
      type: "collection"
    - name: "files"
      type: "string"
    - name: "s3prefixes"
      type: "collection"
    properties:
    - name: "resource"
      value: "arn:aws:lambda:eu-central-1:735406098573:function:bwa-mask"
- parallelFor:
    name: "ParallelFor"
    dataIns:
    - name: "s3bucket"
      type: "string"
      source: "bwa-mask/s3bucket"
      constraints:
      - name: "distribution"
        value: "REPLICATE(*)"
    - name: "s3splitkey"
      type: "string"
      source: "bwa-mask/s3splitkeys"
      constraints:
      - name: "distribution"
        value: "BLOCK(1)"
    - name: "files"
      type: "string"
      source: "bwa-mask/files"
      constraints:
      - name: "distribution"
        value: "REPLICATE(*)"
    - name: "s3prefix"
      type: "string"
      source: "bwa-mask/s3prefixes"
      constraints:
      - name: "distribution"
        value: "BLOCK(1)"
    loopCounter:
      type: "number"
      to: "BWA/numSplits"
      step: "1"
    loopBody:
    - function:
        name: "bwa-index"
        type: "collection"
        dataIns:
        - name: "s3bucket"
          type: "string"
          source: "ParallelFor/s3bucket"
        - name: "s3splitkey"
          type: "string"
          source: "ParallelFor/s3splitkey"
        - name: "files"
          type: "string"
          source: "ParallelFor/files"
        - name: "s3prefix"
          type: "string"
          source: "ParallelFor/s3prefix"
        dataOuts:
        - name: "s3bucket"
          type: "string"
        - name: "files"
          type: "string"
        - name: "s3prefix"
          type: "string"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:eu-central-1:735406098573:function:bwa-index"
    - function:
        name: "bwa-aln"
        type: "Collection"
        dataIns:
        - name: "s3bucket"
          type: "string"
          source: "bwa-index/s3bucket"
        - name: "files"
          type: "string"
          source: "bwa-index/files"
        - name: "s3prefix"
          type: "string"
          source: "bwa-index/s3prefix"
        dataOuts:
        - name: "s3bucket"
          type: "string"
        - name: "files"
          type: "string"
        - name: "s3prefix"
          type: "string"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:eu-central-1:735406098573:function:bwa-aln"
    - function:
        name: "bwa-sampe"
        type: "Collection"
        dataIns:
        - name: "s3bucket"
          type: "string"
          source: "bwa-aln/s3bucket"
        - name: "files"
          type: "string"
          source: "bwa-aln/files"
        - name: "s3prefix"
          type: "string"
          source: "bwa-aln/s3prefix"
        dataOuts:
        - name: "s3bucket"
          type: "string"
        - name: "files"
          type: "string"
        - name: "s3prefix"
          type: "string"
        - name: "s3samkey"
          type: "string"
        properties:
        - name: "resource"
          value: "arn:aws:lambda:eu-central-1:735406098573:function:bwa-sampe"
    dataOuts:
    - name: "s3bucket"
      type: "string"
      source: "bwa-sampe/s3bucket"
    - name: "s3prefix"
      type: "string"
      source: "bwa-sampe/s3prefix"
    - name: "s3samkeys"
      type: "collection"
      source: "bwa-sampe/s3samkey"
- function:
    name: "bwa-merge"
    type: "Collection"
    dataIns:
    - name: "s3bucket"
      type: "string"
      source: "ParallelFor/s3bucket"
    - name: "s3prefix"
      type: "string"
      source: "ParallelFor/s3prefix"
    - name: "s3samkeys"
      type: "collection"
      source: "ParallelFor/s3samkeys"
    dataOuts:
    - name: "s3bucket"
      type: "string"
    - name: "s3prefix"
      type: "string"
    - name: "mergedsamkey"
      type: "string"
    properties:
    - name: "resource"
      value: "arn:aws:lambda:eu-central-1:735406098573:function:bwa-merge"
dataOuts:
- name: "s3bucket"
  type: "string"
  source: "bwa-merge/s3bucket"
- name: "mergedsamkey"
  type: "string"
  source: "bwa-merge/mergedsamkey"
- name: "s3prefix"
  type: "string"
  source: "bwa-merge/s3prefix"
